import argparse
import time
import os

parser = argparse.ArgumentParser()
parser.add_argument("--fold", type=int, required=True)
args = parser.parse_args()

fold = args.fold

print(f"Hello from fold {fold}")

# Write a file so we can confirm execution
with open(f"fold_{fold}_output.txt", "w") as f:
    f.write(f"This file was generated by fold {fold}\n")

# Sleep so job stays visible in squeue
time.sleep(10)

print(f"Fold {fold} finished successfully")
